pomodoro: Optional soundfile to play at every transition

diff --git a/pomodoro b/pomodoro
--- a/pomodoro
+++ b/pomodoro
@@ -3,9 +3,11 @@
 # Pomodoro timer script
 worktime=25
 breaktime=5
-usage="Usage: \e[1m$(basename $0)\e[0m -h | [\e[4mwork\e[0m [\e[4mbreak\e[0m]]"
+soundfile=
+usage="Usage: \e[1m$(basename $0)\e[0m -h | [-s \e[4mfile\e[0m] [\e[4mwork\e[0m [\e[4mbreak\e[0m]]"
 help="Starts a pomodoro timer with given work and break times. Default is 25 and 5 minutes.
-    \e[1m-h\e[0m	Show this help.
+    \e[1m-h\e[0m  	Show this help.
+    \e[1m-s\e[0m \e[4mfile\e[0m	Play the soundfile \e[4mfile\e[0m at every transition.
     \e[1mwork\e[0m	Work time in minutes.
     \e[1mbreak\e[0m	Break time in minutes.
 "
@@ -19,17 +21,23 @@ now() {
   printf "\e[37m$(date +%T)\e[0m $1"
 }
 
-while getopts ":h" opt; do
-    case $opt in
-        h)
+while [[ -n $1 ]]; do
+    case $1 in
+        -h)
             printf "%b\n" "$usage"
             printf "%b\n" "$help"
             exit 0
             ;;
-        \?)
-            die "Invalid option: -$OPTARG"
+        -s)
+            soundfile=$2
+            [[ -r "$soundfile" ]] || die "Not a readable soundfile: $soundfile"
+            shift 1
+            ;;
+        *)
+            die "Invalid option: $1"
             ;;
     esac
+    shift 1
 done
 
 shift $((OPTIND-1))
@@ -65,9 +73,13 @@ while true; do
         printf "What are you going to do now?: "
         read task
     fi
+    [[ -n "$soundfile" ]] && play -q "$soundfile" &
     note $((worktime))m "Work time is up!"
+    [[ -n "$soundfile" ]] && play -q "$soundfile" &
     now "Time for a break :)\n"
     note $((breaktime))m "Break time is up!"
+    [[ -n "$soundfile" ]] && play -q "$soundfile" &
     now "Press enter to start another round"
+    while read -r -t 0; do read -r trash; echo "Found trash: $trash"; done  # Flush the input buffer
     read trash
 done
